[profile.default]
src = 'src'
out = 'out'
libs = ['lib']
#auto_detect_solc = true
solc_version = '0.8.15'
# See more config options https://github.com/foundry-rs/foundry/tree/master/config
via_ir = true
ffi = false

[rpc_endpoints]
mumbai = "${ALCHEMY_MUMBAI_RPC_URL}"

[profile.polygonscan]
mumbai = { key = "${POLYGONSCAN_API_KEY}" }